/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poli.employeesmanagerclient.view;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Esta clase controla toda la interfaz de usuario del cliente.
 * 
 */
public class JFrameChatClient extends javax.swing.JFrame {
    private Socket socket;
    private DataInputStream dataInputStream;
    private DataOutputStream dataOutputStream;
    public static final String CLOSING_ORDER = "Chao";    
    /**
     * Creates new form JFrameChatClient
     */
    public JFrameChatClient() {
        initComponents();
        setTitle("Cliente gestor de empleados");        
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldIp = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonConnect = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jTabbedPaneCRUD = new javax.swing.JTabbedPane();
        jPanelCreate = new javax.swing.JPanel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        jLabelFirstname = new javax.swing.JLabel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jLabelLastname = new javax.swing.JLabel();
        jTextFieldLastname = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelBirthdate = new javax.swing.JLabel();
        jTextFieldBirthdate = new javax.swing.JTextField();
        jLabelSalary = new javax.swing.JLabel();
        jTextFieldSalary = new javax.swing.JTextField();
        jLabelFee = new javax.swing.JLabel();
        jTextFieldFee = new javax.swing.JTextField();
        jLabelPositionId = new javax.swing.JLabel();
        jTextFieldPositionId = new javax.swing.JTextField();
        jLabelDepartmentId = new javax.swing.JLabel();
        jTextFieldDepartmentId = new javax.swing.JTextField();
        ManagerId = new javax.swing.JLabel();
        jTextFieldManagerId = new javax.swing.JTextField();
        jButtonCreate = new javax.swing.JButton();
        jPanelRead = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFindById = new javax.swing.JTextField();
        jButtonFindById = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFindById = new javax.swing.JTable();
        jPanelUpdate = new javax.swing.JPanel();
        jLabelId1 = new javax.swing.JLabel();
        jTextFieldUpdateId = new javax.swing.JTextField();
        jLabelFirstname1 = new javax.swing.JLabel();
        jTextFieldUpdateFirstname = new javax.swing.JTextField();
        jLabelLastname1 = new javax.swing.JLabel();
        jTextFieldUpdateLastname = new javax.swing.JTextField();
        jLabelEmail1 = new javax.swing.JLabel();
        jTextFieldUpdateEmail = new javax.swing.JTextField();
        jLabelBirthdate1 = new javax.swing.JLabel();
        jTextFieldUpdateBirthdate = new javax.swing.JTextField();
        jLabelSalary1 = new javax.swing.JLabel();
        jTextFieldUpdateSalary = new javax.swing.JTextField();
        jLabelFee1 = new javax.swing.JLabel();
        jTextFieldUpdateFee = new javax.swing.JTextField();
        jLabelPositionId1 = new javax.swing.JLabel();
        jTextFieldUpdatePositionId = new javax.swing.JTextField();
        jLabelDepartmentId1 = new javax.swing.JLabel();
        jTextFieldUpdateDepartmentId = new javax.swing.JTextField();
        ManagerId1 = new javax.swing.JLabel();
        jTextFieldUpdateManagerId = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jPanelDelete = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDeleteId = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldIp.setText("localhost");

        jTextFieldPort.setText("9000");

        jLabel1.setText("Dirección IP del servidor:");

        jLabel2.setText("Puerto del servidor:");

        jButtonConnect.setText("Conectar");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre de usuario:");

        jTextFieldUsername.setText("poli00x");

        jPanelCreate.setPreferredSize(new java.awt.Dimension(708, 600));

        jLabelId.setText("Identificación:");

        jLabelFirstname.setText("Primer nombre:");

        jTextFieldFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstnameActionPerformed(evt);
            }
        });

        jLabelLastname.setText("Apellido:");

        jLabelEmail.setText("Email:");

        jLabelBirthdate.setText("Fecha de nacimiento:");

        jTextFieldBirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthdateActionPerformed(evt);
            }
        });

        jLabelSalary.setText("Sueldo:");

        jLabelFee.setText("Comisión:");

        jLabelPositionId.setText("Cargo:");

        jLabelDepartmentId.setText("Departamento:");

        ManagerId.setText("Gerente:");

        jButtonCreate.setText("Crear");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCreateLayout = new javax.swing.GroupLayout(jPanelCreate);
        jPanelCreate.setLayout(jPanelCreateLayout);
        jPanelCreateLayout.setHorizontalGroup(
            jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCreateLayout.createSequentialGroup()
                        .addComponent(jButtonCreate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateLayout.createSequentialGroup()
                        .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCreateLayout.createSequentialGroup()
                                .addComponent(jLabelFirstname)
                                .addGap(85, 85, 85)
                                .addComponent(jTextFieldFirstname))
                            .addGroup(jPanelCreateLayout.createSequentialGroup()
                                .addComponent(jLabelId)
                                .addGap(99, 99, 99)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                            .addGroup(jPanelCreateLayout.createSequentialGroup()
                                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSalary)
                                    .addComponent(jLabelFee)
                                    .addComponent(jLabelPositionId)
                                    .addComponent(jLabelDepartmentId)
                                    .addComponent(ManagerId))
                                .addGap(90, 90, 90)
                                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSalary)
                                    .addComponent(jTextFieldFee)
                                    .addComponent(jTextFieldManagerId)
                                    .addComponent(jTextFieldPositionId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldDepartmentId, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCreateLayout.createSequentialGroup()
                                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLastname)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelBirthdate))
                                .addGap(47, 47, 47)
                                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldLastname)
                                    .addComponent(jTextFieldBirthdate))))
                        .addGap(127, 127, 127))))
        );
        jPanelCreateLayout.setVerticalGroup(
            jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstname)
                    .addComponent(jTextFieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLastname)
                    .addComponent(jTextFieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPositionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPositionId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDepartmentId)
                    .addComponent(jTextFieldDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManagerId)
                    .addComponent(jTextFieldManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCreate)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPaneCRUD.addTab("Crear empleado", jPanelCreate);

        jLabel4.setText("Identificación: ");

        jButtonFindById.setText("Buscar");
        jButtonFindById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindByIdActionPerformed(evt);
            }
        });

        jTableFindById.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificación", "Primer nombre", "Segundo nombre", "Email", "Fecha de nacimiento", "Sueldo", "Comisión", "Cargo", "Departamento", "Gerente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFindById);

        javax.swing.GroupLayout jPanelReadLayout = new javax.swing.GroupLayout(jPanelRead);
        jPanelRead.setLayout(jPanelReadLayout);
        jPanelReadLayout.setHorizontalGroup(
            jPanelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(jPanelReadLayout.createSequentialGroup()
                        .addGroup(jPanelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelReadLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFindById, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonFindById))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelReadLayout.setVerticalGroup(
            jPanelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFindById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonFindById)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPaneCRUD.addTab("Buscar empleado", jPanelRead);

        jLabelId1.setText("Identificación:");

        jLabelFirstname1.setText("Primer nombre:");

        jTextFieldUpdateFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUpdateFirstnameActionPerformed(evt);
            }
        });

        jLabelLastname1.setText("Apellido:");

        jLabelEmail1.setText("Email:");

        jLabelBirthdate1.setText("Fecha de nacimiento:");

        jTextFieldUpdateBirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUpdateBirthdateActionPerformed(evt);
            }
        });

        jLabelSalary1.setText("Sueldo:");

        jLabelFee1.setText("Comisión:");

        jLabelPositionId1.setText("Cargo:");

        jLabelDepartmentId1.setText("Departamento:");

        ManagerId1.setText("Gerente:");

        jButtonUpdate.setText("Actualizar");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdateLayout = new javax.swing.GroupLayout(jPanelUpdate);
        jPanelUpdate.setLayout(jPanelUpdateLayout);
        jPanelUpdateLayout.setHorizontalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpdateLayout.createSequentialGroup()
                        .addComponent(jButtonUpdate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdateLayout.createSequentialGroup()
                        .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                .addComponent(jLabelFirstname1)
                                .addGap(85, 85, 85)
                                .addComponent(jTextFieldUpdateFirstname))
                            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                .addComponent(jLabelId1)
                                .addGap(99, 99, 99)
                                .addComponent(jTextFieldUpdateId, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSalary1)
                                    .addComponent(jLabelFee1)
                                    .addComponent(jLabelPositionId1)
                                    .addComponent(jLabelDepartmentId1)
                                    .addComponent(ManagerId1))
                                .addGap(90, 90, 90)
                                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUpdateSalary)
                                    .addComponent(jTextFieldUpdateFee)
                                    .addComponent(jTextFieldUpdateManagerId)
                                    .addComponent(jTextFieldUpdatePositionId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldUpdateDepartmentId, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelUpdateLayout.createSequentialGroup()
                                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLastname1)
                                    .addComponent(jLabelEmail1)
                                    .addComponent(jLabelBirthdate1))
                                .addGap(47, 47, 47)
                                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUpdateEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldUpdateLastname)
                                    .addComponent(jTextFieldUpdateBirthdate))))
                        .addGap(127, 127, 127))))
        );
        jPanelUpdateLayout.setVerticalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId1)
                    .addComponent(jTextFieldUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstname1)
                    .addComponent(jTextFieldUpdateFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLastname1)
                    .addComponent(jTextFieldUpdateLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdateBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSalary1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdateFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFee1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdatePositionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPositionId1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDepartmentId1)
                    .addComponent(jTextFieldUpdateDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManagerId1)
                    .addComponent(jTextFieldUpdateManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdate)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPaneCRUD.addTab("Actualizar empleado", jPanelUpdate);

        jLabel5.setText("Identificación:");

        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeleteLayout = new javax.swing.GroupLayout(jPanelDelete);
        jPanelDelete.setLayout(jPanelDeleteLayout);
        jPanelDeleteLayout.setHorizontalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDeleteLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonDelete))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanelDeleteLayout.setVerticalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButtonDelete)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jTabbedPaneCRUD.addTab("Eliminar empleado", jPanelDelete);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonConnect)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addContainerGap(465, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButtonConnect)
                .addGap(41, 41, 41)
                .addComponent(jTabbedPaneCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
     * Este método controla la lógica para establecer la conexión del cliente con el servidor de chat desde el botón "Conectar".
     * Una vez disparado el evento de click se genera el hilo principal para conectarse al servidor y recibi los mensajes.
     * @param evt el evento disparado al hacer click en el botón.
     */
    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        try {
            this.socket = new Socket(this.jTextFieldIp.getText(), Integer.parseInt(this.jTextFieldPort.getText()));
            this.dataOutputStream = new DataOutputStream(this.socket.getOutputStream());
            this.dataInputStream = new DataInputStream(this.socket.getInputStream());
            this.dataOutputStream.writeUTF(String.format("1|%s|%s|%s", this.jTextFieldUsername.getText(), this.jTextFieldUsername.getText(), "Servidor"));
            Thread listeningThread = new Thread(new Runnable() {
                @Override
                public void run() {
                    String incomingMessage = "";
                    enableCrudInterface();
                    disableConfigInterface();
                    try {
                        while (socket.isConnected()) {
                            incomingMessage = dataInputStream.readUTF();                            
                            String [] splittedMessage = incomingMessage.split("\\|"); 
                            switch(splittedMessage[0]){
                                case "4":
                                    JOptionPane.showMessageDialog(null, "Empleado creado exitosamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                                    break;
                                case "5":                                    
                                    updateJTableFindyById(splittedMessage[1]);
                                    JOptionPane.showMessageDialog(null, "La búsqueda del empleado ha sido exitosa.", "Información", JOptionPane.INFORMATION_MESSAGE);
                                    break;
                                case "6":
                                    JOptionPane.showMessageDialog(null, "La actualización del empleado ha sido exitosa.", "Información", JOptionPane.INFORMATION_MESSAGE);
                                    break;
                                case "7":
                                    JOptionPane.showMessageDialog(null, "El empleado ha sido eliminado del registro exitosamente, revise el histórico.", "Información", JOptionPane.INFORMATION_MESSAGE);
                                    break;
                                case "8":
                                    JOptionPane.showMessageDialog(null, splittedMessage[1], "Información", JOptionPane.INFORMATION_MESSAGE);
                                    break;
                            }
                        }
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }

            });
            listeningThread.start();            
            JOptionPane.showMessageDialog(null, "Conexión establecida.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(JFrameChatClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jTextFieldBirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBirthdateActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        try {
            String createEmployeeMessage = String.format("%s_%s_%s_%s_%s_%s_%s_%s_%s_%s", this.jTextFieldId.getText()
                    , this.jTextFieldFirstname.getText(), this.jTextFieldLastname.getText(), this.jTextFieldEmail.getText()
                    , this.jTextFieldBirthdate.getText(), this.jTextFieldSalary.getText()
                    , this.jTextFieldFee.getText(), this.jTextFieldPositionId.getText()
                    , this.jTextFieldDepartmentId.getText(), this.jTextFieldManagerId.getText());
            this.dataOutputStream.writeUTF(String.format("4|%s|%s|%s", this.jTextFieldUsername.getText(), createEmployeeMessage, "Servidor"));
        } catch (IOException ex) {
            Logger.getLogger(JFrameChatClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jTextFieldFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstnameActionPerformed

    private void jTextFieldUpdateFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpdateFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateFirstnameActionPerformed

    private void jTextFieldUpdateBirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpdateBirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateBirthdateActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            String updateEmployeeMessage = String.format("%s_%s_%s_%s_%s_%s_%s_%s_%s_%s", this.jTextFieldUpdateId.getText()
                    , this.jTextFieldUpdateFirstname.getText(), this.jTextFieldUpdateLastname.getText(), this.jTextFieldUpdateEmail.getText()
                    , this.jTextFieldUpdateBirthdate.getText(), this.jTextFieldUpdateSalary.getText()
                    , this.jTextFieldUpdateFee.getText(), this.jTextFieldUpdatePositionId.getText()
                    , this.jTextFieldUpdateDepartmentId.getText(), this.jTextFieldUpdateManagerId.getText());
            this.dataOutputStream.writeUTF(String.format("6|%s|%s|%s", this.jTextFieldUsername.getText(), updateEmployeeMessage, "Servidor"));
        } catch (IOException ex) {
            Logger.getLogger(JFrameChatClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonFindByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindByIdActionPerformed
        try {
            String employeeId = this.jTextFieldFindById.getText();            
                this.dataOutputStream.writeUTF(String.format("5|%s|%s|%s", this.jTextFieldUsername.getText(), employeeId, "Servidor"));
        } catch (IOException ex) {
            Logger.getLogger(JFrameChatClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFindByIdActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            String deleteEmployeeMessage = String.format("%s", this.jTextFieldDeleteId.getText());
            this.dataOutputStream.writeUTF(String.format("7|%s|%s|%s", this.jTextFieldUsername.getText(), deleteEmployeeMessage, "Servidor"));
        } catch (IOException ex) {
            Logger.getLogger(JFrameChatClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    /**
     * Este método activa los controles de interfaz de usuario necesarios para configurar una conexión con el servidor (dirección IP, puerto, nombre de usuario y botón para conectar).
     */
    private void enableConfigInterface(){
        if(!this.jTextFieldIp.isEnabled())
            this.jTextFieldIp.setEnabled(true);
         if(!this.jTextFieldPort.isEnabled())
            this.jTextFieldPort.setEnabled(true);
        if(!this.jTextFieldUsername.isEnabled())
            this.jTextFieldUsername.setEnabled(true);
        if(!this.jButtonConnect.isEnabled())
            this.jButtonConnect.setEnabled(true);
    }
    /**
     * Este método desactiva los controles de interfaz de usuario necesarios para configurar una conexión con el servidor (dirección IP, puerto, nombre de usuario y botón para conectar).
     */
    private void disableConfigInterface(){
        if(this.jTextFieldIp.isEnabled())
            this.jTextFieldIp.setEnabled(false);
        if(this.jTextFieldPort.isEnabled())
            this.jTextFieldPort.setEnabled(false);
        if(this.jTextFieldUsername.isEnabled())
            this.jTextFieldUsername.setEnabled(false);
        if(this.jButtonConnect.isEnabled())
            this.jButtonConnect.setEnabled(false);
    }
    /**
     * Este método activa los controles de interfaz de usuario necesarios para enviar y recibir mensajes (campo de texto de mensaje, campo de texto para destinatario y botón para enviar).
     */
    private void enableCrudInterface(){
        if(!this.jTabbedPaneCRUD.isEnabled())
            this.jTabbedPaneCRUD.setEnabled(true);
    }
    /**
     * Este método desactiva los controles de interfaz de usuario necesarios para enviar y recibir mensajes (campo de texto de mensaje, campo de texto para destinatario y botón para enviar).
     */
    private void disableCrudInterface(){
        if(this.jTabbedPaneCRUD.isEnabled())
            this.jTabbedPaneCRUD.setEnabled(false);
    }
    /**
     * Cierra de forma adecuada los flujos de entrada/salida de datos y el socket de conexión con el servidor.
     * @param socket el socket TCP de conexión.
     * @param dataInputStream el flujo de entrada de datos.
     * @param dataOutputStream el flujo de salida de datos.
     */
    public void closeEverything(Socket socket, DataInputStream dataInputStream, DataOutputStream dataOutputStream) {
        try {
            if (dataInputStream != null) {
                dataInputStream.close();
            }
            if (dataOutputStream != null) {
                dataOutputStream.close();
            }
            if (socket != null) {
                socket.close();
            }
        } catch (IOException e) {
            Logger.getLogger(JFrameChatClient.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void updateJTableFindyById(String employeeString){
        String[] employeeStringArray = employeeString.split("_");
        try{
        for(int i=0; i<employeeString.length();i++)
            this.jTableFindById.getModel().setValueAt(employeeStringArray[i], 0, i);
        } catch(Exception e){
            Logger.getLogger(JFrameChatClient.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameChatClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManagerId;
    private javax.swing.JLabel ManagerId1;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFindById;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelBirthdate1;
    private javax.swing.JLabel jLabelDepartmentId;
    private javax.swing.JLabel jLabelDepartmentId1;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelFee;
    private javax.swing.JLabel jLabelFee1;
    private javax.swing.JLabel jLabelFirstname;
    private javax.swing.JLabel jLabelFirstname1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelLastname;
    private javax.swing.JLabel jLabelLastname1;
    private javax.swing.JLabel jLabelPositionId;
    private javax.swing.JLabel jLabelPositionId1;
    private javax.swing.JLabel jLabelSalary;
    private javax.swing.JLabel jLabelSalary1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCreate;
    private javax.swing.JPanel jPanelDelete;
    private javax.swing.JPanel jPanelRead;
    private javax.swing.JPanel jPanelUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneCRUD;
    private javax.swing.JTable jTableFindById;
    private javax.swing.JTextField jTextFieldBirthdate;
    private javax.swing.JTextField jTextFieldDeleteId;
    private javax.swing.JTextField jTextFieldDepartmentId;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFee;
    private javax.swing.JTextField jTextFieldFindById;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIp;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldManagerId;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldPositionId;
    private javax.swing.JTextField jTextFieldSalary;
    private javax.swing.JTextField jTextFieldUpdateBirthdate;
    private javax.swing.JTextField jTextFieldUpdateDepartmentId;
    private javax.swing.JTextField jTextFieldUpdateEmail;
    private javax.swing.JTextField jTextFieldUpdateFee;
    private javax.swing.JTextField jTextFieldUpdateFirstname;
    private javax.swing.JTextField jTextFieldUpdateId;
    private javax.swing.JTextField jTextFieldUpdateLastname;
    private javax.swing.JTextField jTextFieldUpdateManagerId;
    private javax.swing.JTextField jTextFieldUpdatePositionId;
    private javax.swing.JTextField jTextFieldUpdateSalary;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
